# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruise" do
  name "cruise"
  desc "Cruise is a powerful, intuitive, and fully-featured container management TUI (Terminal
User Interface)"
  homepage "https://cruise-org.github.io"
  version "1.2.0-rc2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruise"

  on_macos do
    on_intel do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Darwin_x86_64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "74f27b9a86b5840a589110c167c5e897caa60310a872af19166a52585925aa48"
    end
    on_arm do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Darwin_arm64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "26b00d49835c3e2513f7e0e6fba60faa976a256bfeddadc3c101c418659c3cd1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Linux_x86_64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "0b5d3fdfdc5927f69b134eec659a834b9c54036961029ad416a74271d38c0518"
    end
    on_arm do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Linux_arm64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "b51696c8d29a4245bb341c774e15a86103e9c85e575c05205c57b34816df0dea"
    end
  end

  # No zap stanza required
end
