# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruise" do
  name "cruise"
  desc "Cruise is a powerful, intuitive, and fully-featured container management TUI (Terminal
User Interface)"
  homepage "https://cruise-org.github.io"
  version "1.2.0-rc3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruise"

  on_macos do
    on_intel do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Darwin_x86_64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "37ccb0e4ef02103963013bce710c4f90f4c8ac6e6b8b2393f974098e9b7afa9e"
    end
    on_arm do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Darwin_arm64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "160eff7ca8d6ad64b271f79dba4443751595f961dacb6aca7a15d28752aefb5c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Linux_x86_64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "341ad0be03a20dd26b6834641e475c57f9ced4bf5666c9fe7653fbd3fa948064"
    end
    on_arm do
      url "https://github.com/cruise-org/cruise/releases/download/v#{version}/cruise_Linux_arm64.tar.gz",
        verified: "github.com/cruise-org/cruise"
      sha256 "a8e27c977ccba86de97fafd921270f404fa35e62ab6aea76332a6c96a2ec29c8"
    end
  end

  # No zap stanza required
end
